# Generated by Django 4.0.5 on 2022-06-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedimage',
            name='image',
            field=models.ImageField(db_column='image', upload_to='scraped_images/', verbose_name='Image'),
        ),
    ]
